// Copyright 2026 Netdata Inc. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

package gosnmp

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

// The codec characterization tests pin the observable behavior of the public
// encode and decode entry points, known bugs included, in golden files under
// testdata/codec. Each golden file is a list of cases:
//
//	== <case name>
//	<dump line>
//	...
//
// Decoded numbers use int and uint, so some results depend on the platform
// word size. <name>.golden holds the 64-bit results; <name>.int32.golden holds
// only the cases whose 32-bit results differ, and overrides <name>.golden on
// 32-bit platforms. Regenerate with -update on both word sizes, for example:
//
//	go test -run 'Characterization' -update .
//	GOARCH=386 go test -run 'Characterization' -update .   (on linux/amd64)

var updateGolden = flag.Bool("update", false, "rewrite the codec characterization golden files in testdata/codec")

const goldenDir = "testdata/codec"

// goldenCase is one named result of a characterization test.
type goldenCase struct {
	name string
	dump string
}

// goldenSection is one parsed golden file entry.
type goldenSection struct {
	name string
	dump string
}

// checkGolden compares cases with testdata/codec/<file>.golden (plus the
// 32-bit override file on 32-bit platforms), or rewrites the golden file for
// the running word size when -update is set.
func checkGolden(t *testing.T, file string, cases []goldenCase) {
	t.Helper()

	seen := make(map[string]bool, len(cases))
	for _, c := range cases {
		if seen[c.name] {
			t.Fatalf("duplicate characterization case %q", c.name)
		}
		seen[c.name] = true
	}

	basePath := filepath.Join(goldenDir, file+".golden")
	int32Path := filepath.Join(goldenDir, file+".int32.golden")

	if *updateGolden {
		updateGoldenFiles(t, file, basePath, int32Path, cases)
		return
	}

	want, err := readGoldenMap(basePath)
	if err != nil {
		t.Fatalf("%v (regenerate with -update)", err)
	}
	if strconv.IntSize == 32 {
		overrides, err := readGoldenMap(int32Path)
		if err != nil {
			t.Fatalf("%v (regenerate with GOARCH=386 and -update)", err)
		}
		for name, dump := range overrides {
			if _, ok := want[name]; !ok {
				t.Errorf("%s: case %q is not in %s", int32Path, name, basePath)
			}
			want[name] = dump
		}
	}

	for _, c := range cases {
		wantDump, ok := want[c.name]
		if !ok {
			t.Errorf("case %q is missing from %s (regenerate with -update)", c.name, basePath)
			continue
		}
		if wantDump != c.dump {
			assert.Equal(t, wantDump, c.dump, "case %q differs from %s", c.name, basePath)
		}
	}
	for name := range want {
		if !seen[name] {
			t.Errorf("%s: case %q no longer exists (regenerate with -update)", basePath, name)
		}
	}
}

func updateGoldenFiles(t *testing.T, file, basePath, int32Path string, cases []goldenCase) {
	t.Helper()

	if strconv.IntSize == 64 {
		header := fmt.Sprintf("# Codec characterization results (%s), 64-bit platforms. Generated by go test -update; do not edit.\n", file)
		writeGoldenFile(t, basePath, header, cases)
		return
	}

	base, err := readGoldenMap(basePath)
	if err != nil {
		t.Fatalf("%v (regenerate on a 64-bit platform first)", err)
	}
	var overrides []goldenCase
	for _, c := range cases {
		dump, ok := base[c.name]
		if !ok {
			t.Fatalf("case %q is missing from %s (regenerate on a 64-bit platform first)", c.name, basePath)
		}
		if dump != c.dump {
			overrides = append(overrides, c)
		}
	}
	header := fmt.Sprintf("# Codec characterization results (%s) that differ on 32-bit platforms. Generated by go test -update; do not edit.\n", file)
	writeGoldenFile(t, int32Path, header, overrides)
}

func writeGoldenFile(t *testing.T, path, header string, cases []goldenCase) {
	t.Helper()

	var buf bytes.Buffer
	buf.WriteString(header)
	for _, c := range cases {
		fmt.Fprintf(&buf, "\n== %s\n%s\n", c.name, c.dump)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d cases)", path, len(cases))
}

func readGoldenMap(path string) (map[string]string, error) {
	sections, err := readGoldenFile(path)
	if err != nil {
		return nil, err
	}
	m := make(map[string]string, len(sections))
	for _, s := range sections {
		if _, ok := m[s.name]; ok {
			return nil, fmt.Errorf("%s: duplicate case %q", path, s.name)
		}
		m[s.name] = s.dump
	}
	return m, nil
}

func readGoldenFile(path string) ([]goldenSection, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var sections []goldenSection
	var lines []string
	flush := func() {
		if len(sections) == 0 {
			return
		}
		for len(lines) > 0 && lines[len(lines)-1] == "" {
			lines = lines[:len(lines)-1]
		}
		sections[len(sections)-1].dump = strings.Join(lines, "\n")
		lines = nil
	}

	sc := bufio.NewScanner(bytes.NewReader(data))
	sc.Buffer(nil, 1<<20)
	for sc.Scan() {
		line := sc.Text()
		switch {
		case strings.HasPrefix(line, "== "):
			flush()
			sections = append(sections, goldenSection{name: strings.TrimPrefix(line, "== ")})
		case len(sections) == 0:
			if line != "" && !strings.HasPrefix(line, "#") {
				return nil, fmt.Errorf("%s: unexpected line before the first case: %q", path, line)
			}
		default:
			lines = append(lines, line)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	flush()
	return sections, nil
}

// codecSentinels are the exported errors a codec result is matched against.
var codecSentinels = []struct {
	name string
	err  error
}{
	{"ErrBase128IntegerTooLarge", ErrBase128IntegerTooLarge},
	{"ErrBase128IntegerTruncated", ErrBase128IntegerTruncated},
	{"ErrFloatBufferTooShort", ErrFloatBufferTooShort},
	{"ErrFloatTooLarge", ErrFloatTooLarge},
	{"ErrIntegerTooLarge", ErrIntegerTooLarge},
	{"ErrInvalidOidLength", ErrInvalidOidLength},
	{"ErrInvalidPacketLength", ErrInvalidPacketLength},
	{"ErrZeroByteBuffer", ErrZeroByteBuffer},
	{"ErrZeroLenInteger", ErrZeroLenInteger},
	{"ErrDecryption", ErrDecryption},
	{"ErrInvalidMsgs", ErrInvalidMsgs},
	{"ErrNotInTimeWindow", ErrNotInTimeWindow},
	{"ErrUnknownEngineID", ErrUnknownEngineID},
	{"ErrUnknownPDUHandlers", ErrUnknownPDUHandlers},
	{"ErrUnknownReportPDU", ErrUnknownReportPDU},
	{"ErrUnknownSecurityLevel", ErrUnknownSecurityLevel},
	{"ErrUnknownSecurityModels", ErrUnknownSecurityModels},
	{"ErrUnknownUsername", ErrUnknownUsername},
	{"ErrWrongDigest", ErrWrongDigest},
}

// dumpError describes an error by the exported sentinels it matches; the
// message text is not part of the pinned behavior.
func dumpError(err error) string {
	var matched []string
	for _, s := range codecSentinels {
		if errors.Is(err, s.err) {
			matched = append(matched, s.name)
		}
	}
	if len(matched) == 0 {
		return "error"
	}
	return "error (" + strings.Join(matched, ", ") + ")"
}

// observe runs fn and reports whether it panicked and whether it wrote to
// os.Stdout, which the library does when it recovers from some panics. It
// swaps the global os.Stdout, so tests that use it must not run in parallel
// with others.
func observe(fn func()) (panicked, wroteStdout bool) {
	r, w, err := os.Pipe()
	if err != nil {
		panic(err)
	}
	written := make(chan int64)
	go func() {
		n, _ := io.Copy(io.Discard, r)
		_ = r.Close()
		written <- n
	}()

	stdout := os.Stdout
	os.Stdout = w
	func() {
		defer func() {
			if recover() != nil {
				panicked = true
			}
		}()
		fn()
	}()
	os.Stdout = stdout
	_ = w.Close()

	return panicked, <-written > 0
}

// dumpBytesLimit is the length above which dumpBytes abbreviates its output.
const dumpBytesLimit = 1024

// dumpBytes prints a byte slice in hex, telling nil and empty apart. Long
// slices are pinned by their first bytes, length and SHA-256.
func dumpBytes(b []byte) string {
	switch {
	case b == nil:
		return "nil"
	case len(b) == 0:
		return "empty"
	case len(b) > dumpBytesLimit:
		return fmt.Sprintf("%x... (%d bytes, sha256 %x)", b[:64], len(b), sha256.Sum256(b))
	default:
		return fmt.Sprintf("%x", b)
	}
}
